import { APPLICATION_NAME } from "@/constants";

const Terms = () => {
  return (
    <main className="container mx-auto px-4 py-16">
      <div className="max-w-3xl mx-auto space-y-8">
        <div className="border-b pb-8">
          <h1 className="text-3xl font-bold tracking-tight mb-4">
            Terms of Service
          </h1>
          <p className="text-muted-foreground">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </div>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">
            1. Acceptance of Terms
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            By accessing and using {APPLICATION_NAME} ("the Service"), you
            accept and agree to be bound by the terms and provision of this
            agreement. If you do not agree to abide by these terms, please do
            not use this Service.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">
            2. Description of Service
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            {APPLICATION_NAME} provides AI-powered user interface generation
            tools. The Service allows users to input text prompts and receive
            generated code artifacts. The Service includes features such as code
            streaming, component variations, and export capabilities.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">
            3. User Conduct
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            You agree to use the Service only for lawful purposes. You are
            prohibited from using the Service to generate content that is
            illegal, harmful, threatening, abusive, harassment, tortious,
            defamatory, vulgar, obscene, libelous, invasive of another's
            privacy, hateful, or racially, ethnically or otherwise
            objectionable.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">
            4. Generated Content & Intellectual Property
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            The code and designs generated by {APPLICATION_NAME} are provided to
            you with a flexible usage license. You are free to use, modify, and
            distribute the generated code in your personal and commercial
            projects.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            However, the underlying software, design of the Service, and all
            other content provided by us (excluding your generated content) are
            protected by copyright, trademark, and other intellectual property
            laws.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">
            5. Disclaimer of Warranties
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            The Service is provided on an "as is" and "as available" basis.{" "}
            {APPLICATION_NAME} expressly disclaims all warranties of any kind,
            whether express or implied, including, but not limited to the
            implied warranties of merchantability, fitness for a particular
            purpose and non-infringement.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            We make no warranty that (i) the Service will meet your
            requirements, (ii) the Service will be uninterrupted, timely,
            secure, or error-free, or (iii) the results that may be obtained
            from the use of the Service will be accurate or reliable.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">
            6. Limitation of Liability
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            You expressly understand and agree that {APPLICATION_NAME} shall not
            be liable for any direct, indirect, incidental, special,
            consequential or exemplary damages, including but not limited to,
            damages for loss of profits, goodwill, use, data or other intangible
            losses resulting from the use or the inability to use the Service.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">
            7. Changes to Terms
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            We reserve the right to update or modify these Terms of Service at
            any time without prior notice. Your continued use of the Service
            after any such changes constitutes your acceptance of the new Terms
            of Service.
          </p>
        </section>
      </div>
    </main>
  );
};

export default Terms;
